#!/usr/bin/env bash
#
# scripts/setup-env.sh — rebuild this repo's .env on a machine that has never
# had one, without a secret ever travelling through git, Drive or a password
# manager.
#
# Every value already exists in Azure as an app setting. `az` can read them, so
# the only credential you carry to a new laptop is your own Azure login. That
# is the whole idea: `az login`, run this, `npm run dev`.
#
#   bash scripts/setup-env.sh                # write .env pointed at DEV
#   bash scripts/setup-env.sh --force        # overwrite an existing .env
#   bash scripts/setup-env.sh --print-prod-db  # print the PROD url, write nothing
#
# WHY DEV AND NOT PRODUCTION
#
# Prisma CLI, tsx scripts and vitest all read `.env` and ignore `.env.local`.
# On the original Mac `.env` holds the production connection string, so a test
# that writes, or a stray `prisma migrate dev`, lands on the live database —
# that has been a near miss more than once. A machine bootstrapped by this
# script has DEV in `.env`, so every one of those paths is safe by default and
# production has to be reached deliberately, via --print-prod-db.
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RG="rg-naimisha-bhajan-roster"
DEV_APP="naimisha-bhajan-roster-dev"
PROD_APP="naimisha-bhajan-roster"
OUT="$REPO/.env"
FORCE=0
MODE="dev"

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --print-prod-db) MODE="print-prod-db" ;;
    -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

if ! command -v az >/dev/null 2>&1; then
  echo "az not found. Install it first:  brew install azure-cli" >&2
  exit 1
fi
if ! az account show >/dev/null 2>&1; then
  echo "Not signed in to Azure. Run:  az login" >&2
  exit 1
fi

settings() {  # $1 = app name -> JSON array of {name,value}
  az webapp config appsettings list --name "$1" --resource-group "$RG" -o json
}

if [ "$MODE" = "print-prod-db" ]; then
  # Deliberately stdout-only. Use it inline and let it die with the command:
  #   DATABASE_URL="$(bash scripts/setup-env.sh --print-prod-db)" npx prisma migrate deploy
  settings "$PROD_APP" | python3 -c '
import json,sys
for s in json.load(sys.stdin):
    if s["name"] == "DATABASE_URL":
        print(s["value"]); break
else:
    sys.exit("DATABASE_URL not found on the production app")'
  exit 0
fi

if [ -e "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo "$OUT already exists. Inspect it first — on the original Mac it holds" >&2
  echo "the PRODUCTION connection string. Re-run with --force to replace it." >&2
  exit 1
fi

echo "Reading app settings from $DEV_APP ..."
settings "$DEV_APP" | OUT="$OUT" python3 -c '
import json, os, secrets, sys

# Taken from the dev app service as-is.
KEEP = ["DATABASE_URL", "DIRECT_URL", "AUTH_SECRET", "AUTH_TRUST_HOST",
        "GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET",
        "VAPID_PUBLIC_KEY", "VAPID_PRIVATE_KEY", "VAPID_SUBJECT", "APP_ENV"]

# Left behind on purpose:
#   NODE_ENV                     setting it in .env breaks `next dev`
#   AUTH_URL / NEXTAUTH_URL      point at the azure host; localhost is set below
#   REQUIRE_SIGN_IN              forced false below so a local run needs no Google
#   CANONICAL_HOST               prod-only; would 308 a local page away
#   NUDGE_SECRET                 for the scheduled nudge, not for a local run
#   WEBSITE_* / SCM_*            App Service plumbing, meaningless off Azure

vals = {s["name"]: s["value"] for s in json.load(sys.stdin)}
missing = [k for k in KEEP if k not in vals]
if missing:
    sys.exit("missing from the dev app service: " + ", ".join(missing))

lines = [
  "# Generated by scripts/setup-env.sh from the naimisha-bhajan-roster-dev",
  "# app service. Gitignored. Re-run that script to rebuild it; do not hand-edit",
  "# the secrets, edit them in Azure so both places stay in step.",
  "#",
  "# >>> THIS FILE POINTS AT THE DEV DATABASE (naimisha_dev). <<<",
  "# The original Mac is the other way round: there, .env is PRODUCTION. Run",
  "# `npm run env:which` if you are ever unsure which one you are about to hit.",
  "",
]
for k in KEEP:
    lines.append(f"{k}={json.dumps(vals[k])}")

lines += [
  "",
  "# Local-run overrides. None of these come from Azure.",
  "AUTH_URL=\"http://localhost:3111\"",
  "REQUIRE_SIGN_IN=\"false\"",
  "XLSX_PATH=\"data/roster.xlsx\"",
  "",
  "# Access-link keys. The dev app service has none, so these are generated",
  "# locally and mean nothing anywhere else. Visit /?k=<key> to take the role.",
  f"EDITOR_KEY={json.dumps(secrets.token_urlsafe(18))}",
  f"MEMBER_KEY={json.dumps(secrets.token_urlsafe(18))}",
  "",
]
out = os.environ["OUT"]
with open(out, "w") as f:
    f.write("\n".join(lines))
os.chmod(out, 0o600)
print("wrote " + out)
' || { echo "failed to write $OUT" >&2; exit 1; }

echo
echo "Done. Next:"
echo "  npm ci"
echo "  npm run env:which     # confirm it says naimisha_dev"
echo "  npm run dev"
